#Numpy Basic


# Creating A Numpy Array and IOts Attribute

In [53]:
#import numpy library
import numpy as np
#creating a list
my_list = [1,2,3,4,5]
#changing the list into a 1-D numpy array
my_array = np.array(my_list)
#printing the array
print(my_array)

#Creating a 0-D numpy array
zero_array = np.array(42)
print(zero_array)

#insteaad of creating a list on seprate varaible we can directly pass that list to .array() function like this
my_array = np.array([1,2,3,4,5])
print(my_array)

#lets create a 2-D array
two_d_array = np.array([[1,2,3],[4,5,6]])
print(two_d_array)

#lets create a 3-D array
three_d_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_d_array)

[1 2 3 4 5]
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#lets create an array and see its attribute
my_array = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(my_array)
print(my_array.ndim) #DIMENSION OF THE ARRAY
print(my_array.shape) #SHAOE IF THE ARRAY
print(my_array.dtype) #TYPE OF ARRAY
print(my_array.size) #SIZE OF THE ARRAY


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
(1, 3, 3)
int64
9


#Accessing and manupulating elements in array

In [ ]:
#lets create a 1-D array and print one of its element
one_arr = np.array([1,2,3,4,5,6])
print(one_arr[4])

#lets print using negative index
print(one_arr[-3])

5
4


In [ ]:
# lets do 2D array
two_arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(two_arr[1,2])

#lets do 3D array
three_arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(three_arr[1,0,0])

#negative indexing
print(three_arr[1,0,-1])

8
7
9


#Slicing array
#some important slicing concept

#array[start:end]
#array[start:end:steps]


In [ ]:
#slicing array from 0 to 8 index
my_new_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(my_new_array[0:8])

#slicing with steps
print(my_new_array[0:-1:2])

[1 2 3 4 5 6 7 8]
[1 3 5 7 9]


In [38]:
#slicing on a 2D array
my_new_2D_array = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(my_new_2D_array[0,3:5],my_new_2D_array[1,0:1])

[4 5] [6]


# Create an array with list [7,14,21,28] and print the array

In [39]:
list_array = np.array([7,14,21,28])
print(list_array)

[ 7 14 21 28]


# Create a 2D array and print its shape and dimension

In [41]:
two_d_arr = np.array([[5,10,15],[20,25,30]])
print(two_d_arr)
print(two_d_arr.shape)
print(two_d_arr.ndim)

[[ 5 10 15]
 [20 25 30]]
(2, 3)
2


In [50]:
print(np.zeros((2,3)))
print(np.arange(0,12,3))

[[0. 0. 0.]
 [0. 0. 0.]]
[0 3 6 9]


In [ ]:
my_list = np.array([2,4,6,8])

